### ISSUE TITLE
sync.py crashes if module.zip from update.json does not exist

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo#1]
If you check `https://raw.githubusercontent.com/kdrag0n/safetynet-fix/master/update.json`, the module's ZIP file does not exist. This causes `sync.py` to crash after it removed the previous ZIP:

```
  File "sync.py", line 152, in <module>
    main()
  File "sync.py", line 146, in main
    sync.pull()
  File "sync.py", line 100, in pull
    self.upload_from_json(item, update_json)
  File "sync.py", line 60, in upload_from_json
    self.update_info(item, t_file)
  File "sync.py", line 46, in update_info
    prop = get_props(file).dict
  File "/mnt/data/web/ftp/repo/magisk/util/file.py", line 35, in __init__
    z = ZipFile(file, "r")
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/xxxx/modules/safetynet-fix/safetynet-fix.zip'
```
So maybe `sync.py`should first backup the previous state to restore to that in case the download fails (like in this case due to the fact that the ZIP was obviously removed from the release – as it worked about an hour ago). A second module to check with, same issue: `https://raw.githubusercontent.com/Kingsman44/Pixelify/master/module/update.json`.

While on it, it might be a good idea to have a way to (temporarily) disable a module (so in this case e.g. until the download URL was fixed).

**Comment by ya0211** [comment]
There is new issue [#1](https://github.com/ya0211/magisk-modules-repo-util/issues/1#issue-1523722567) opened in [magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util) about the repo, the issue will be closed.
