### ISSUE TITLE
compatibility with established repos?

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo#2]
I've just checked the JSON of the "Magisk Modules Alt Repo" (see [here](https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/json/main/modules.json)) and notice the structure looks a bit different from yours:

```json
{
    "last_update": 1598596016000,
    "modules": [
        {
            "id": "0_MARS_SOM_CLEANER-GEAR_ZERO",
            "last_update": 1673042580000,
            "notes_url": "https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/0_MARS_SOM_CLEANER-GEAR_ZERO/main/README.md",
            "prop_url": "https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/0_MARS_SOM_CLEANER-GEAR_ZERO/main/module.prop",
            "stars": 2,
            "zip_url": "https://github.com/Magisk-Modules-Alt-Repo/0_MARS_SOM_CLEANER-GEAR_ZERO/archive/main.zip"
        }
    ],
    "name": "Magisk Modules Alt Repo"
}
```

Will MRepo understand that structure as well? Will the JSON created by the tools here understood by other repo browsers (e.g. [MMRL](https://github.com/DerGoogler/MMRL))? Should `sync.py` maybe create/maintain a second JSON compatible to the "big ones" (see e.g. [here](https://github.com/Googlers-Repo/Magisk-Module-Repo-Builder/blob/master/build.sh) for embedded Python code)?

**Comment by ya0211** [comment]
- These can be supported in future versions, and different data structures need to be converted into what MRepo needs. Before that, I will first improve my own repo, then ensure a usable repo under my control.
- `host.json` (controls module versions and sources, owner-controlled with [ya0211/magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util.git) and `modules.json` (auto-generated) will be separated

**Comment by IzzySoft** [comment]
> These can be supported in future versions, and different data structures need to be converted into what MRepo needs.

That'd be great, thanks! As currently apart from MRepo I know of only one other client permitting to add custom repos ([MMRL](https://github.com/DerGoogler/MMRL)), it's not yet critical. And when adding custom repos one (hopefully) can supply the full URL to the JSON, so there's no conflict if one wants to serve both formats.

> `hosts.json` (controls module versions and sources

Ah, so you're going to split up `modules.json` to separate the details needed by [ya0211/magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util.git) for maintenance, and (I assume) adopt the format already used by other repos for MRepo? That sounds absolutely reasonable and will avoid confusion, yes.

Thanks for all the effort you put into this, much appreciated! To not cause confusion, I'll wait until things have settled (the open points we've discussed so far) before starting to look at things I've considered to add (e.g. if one runs an own server, one would not need a "forge" like Github to host the repo but rather wants to e.g. `rsync` the files to the own server – which is what I plan to do. I might give it a try myself then, though my Python knowledge got a bit rusty meanwhile, but first wait until you have the "base" ready).

**Comment by ya0211** [comment]
- I plan that compatibility with established repos will be handled by the app
- This part will not start until the new `sync.py` is completed
